# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Instruction_memory/Instruction_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Instruction_memory || ORIG_REF_NAME==Instruction_memory} -quiet] -quiet

# XDC: ip/Instruction_memory/Instruction_memory_ooc.xdc
