# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Facultad/Arquitectura de Computadoras/Practicos Vivado/tp_final_pipeline/tp_final_pipeline.srcs/sources_1/ip/Data_Memory/Data_Memory.xci
# IP: The module: 'Data_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/Arquitectura de Computadoras/Practicos Vivado/tp_final_pipeline/tp_final_pipeline.srcs/sources_1/ip/Data_Memory/Data_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Facultad/Arquitectura de Computadoras/Practicos Vivado/tp_final_pipeline/tp_final_pipeline.srcs/sources_1/ip/Data_Memory/Data_Memory.xci
# IP: The module: 'Data_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/Arquitectura de Computadoras/Practicos Vivado/tp_final_pipeline/tp_final_pipeline.srcs/sources_1/ip/Data_Memory/Data_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
